### ISSUE TITLE
How to test zipf distribution?

### ISSUE THREAD

**Issue by SHTUSIST** [luziyi23/p2KVS#3]
Inspiring Work. 

May I ask how you let rocksdb db_bench test the zipf distribution?

**Comment by luziyi23** [comment]
Currently RocksDB db_bench does not support zipf. We use [YCSB](https://github.com/brianfrankcooper/YCSB) traces to test zipf distribution. However, now I don't think this method is convenient. 
If you want to test the zifp distribution, I suggest directly use [YCSB-cpp](https://github.com/ls4154/YCSB-cpp) or refer to its code ([zipfian_generator.h](https://github.com/ls4154/YCSB-cpp/blob/master/core/zipfian_generator.h)) to modify the key generator in db_bench.

**Comment by SHTUSIST** [comment]
> Currently RocksDB db_bench does not support zipf. We use [YCSB](https://github.com/brianfrankcooper/YCSB) traces to test zipf distribution. However, now I don't think this method is convenient. If you want to test the zifp distribution, I suggest directly use [YCSB-cpp](https://github.com/ls4154/YCSB-cpp) or refer to its code ([zipfian_generator.h](https://github.com/ls4154/YCSB-cpp/blob/master/core/zipfian_generator.h)) to modify the key generator in db_bench.

Thx
