### ISSUE TITLE
Compilation Error when making write_test

### ISSUE THREAD

**Issue by SHTUSIST** [luziyi23/p2KVS#4]
Sorry bother again. 

I  successully make rocksdb and make install it as README.md said. 

However, when make write_test, I meet the below problems. After run make write_test 

> g++ write_test.cpp -O3 -std=c++14 -lpthread -mcmodel=medium -lrocksdb -ldl  -lbz2 -lsnappy -lz -o write_test -DTOTAL_NUM=10000000 -DQUEUE_NUM=8
/tmp/ccg0BnX6.o: In function `worker_thread(int, rocksdb::DB*)':
write_test.cpp:(.text+0x548): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:36: write_test] Error 1

Could you give some ideas?

**Comment by luziyi23** [comment]
Sorry I can't reproduce this error.
In the code I use the default constructor of `rocksdb::WriteBatch` (line 146`rocksdb::WriteBatch batch;`) instead of the one with two unsigned long parameters.

**Comment by SHTUSIST** [comment]
> Sorry I can't reproduce this error. In the code I use the default constructor of `rocksdb::WriteBatch` (line 146`rocksdb::WriteBatch batch;`) instead of the one with two unsigned long parameters.

Could you give your g++ version?

My compilation steps is as follows, is any problems here?

make install -j64  (successfully installed)
make write_test DATANUM=32000000 INSTNUM=8

**Comment by luziyi23** [comment]
I have successfully compiled it with both g++9.4.0 and 10.4.0 before.

**Comment by SHTUSIST** [comment]
> I have successfully compiled it with both g++9.4.0 and 10.4.0 before.

After switching to this new version, I have successfully made the compilation.

Could you tell me how to test p2kvs with db_bench? Just using ./db_bench? We may refer your paper in our new work and make an evalution in the expirement part. 

Thx a lot. (BTW, write_test is a little simple. We may make a complicated test and db_bench could satisfy our need)

**Comment by luziyi23** [comment]
Sorry we didn't integrate p2kvs into db_bench. Just for your information, maybe you can simulate the ideal optimal performance of p2kvs by running multiple db_bench process simultaneously, each with different db path (--db option) and batch writing turned on (set --batch_size to a proper value, such as 8 or 32 in our paper).
